language: java
jdk:
  - openjdk8
  - openjdk9
sudo: false # faster builds

script: "mvn cobertura:cobertura"
script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - douglas.ferma8@gmail.com
    - douglasfm8@hogmail.com
